services:
  chatbot:
      build:
        context: .
        dockerfile: Dockerfile
      image: ${IMAGE_NAME:-chatbot:latest}
      environment:
        - OPENAI_API_KEY=$OPENAI_API_KEY
        - GRADIO_SERVER_NAME=${GRADIO_SERVER_NAME:-0.0.0.0}
      container_name: chatbot
      ports:
        - ${HOST_SERVER_PORT:-8000}:7860
      volumes:
        - ${HOST_DATA_DIR:-/home/deployer/chatbot/data/raw}:/app/data/raw
        - ${HOST_VECTORSTORE:-/home/deployer/chatbot/vectorstore}:/app/vectorstore
      restart: always
